name=AvantLumi
version=0.2.10
author=AvantMaker.com
maintainer=AvantMaker.com <info@avantmaker.com>
sentence=Advanced FastLED-based library for easy LED strip control with palettes, waver effects, and JSON status.
paragraph=AvantLumi is an Arduino library for FastLED-compatible LED strips, offering color palettes, brightness, fade effects, and status reporting. No network dependencies. Includes example sketches.
category=Display
url=https://avantmaker.com/
architectures=esp32,avr
includes=AvantLumi.h
depends=FastLED
